### PR TITLE
Fix failed Filter null check due to constraints change under nested column pruning

### PR DESCRIPTION
**Pull request by viirya**
## What changes were proposed in this pull request?

Correct null check logic in `FilterExec` doesn't work anymore if we move to nested column pruning, especially for the change in `IsNotNull` constraints.

Assume there is a constraint `IsNotNull(a.b)` and the filter predicates are `a.b > 1 && IsNotNull(a.b)`. `FilterExec` will set the nullability of its output attribute `a` to false and use this output to generate predicate codes. Since `a` is non-nullable now and the gen'd code of `a.b > 1` doesn't check if `a` can be null or not now. `FilterExec` normally will put the null check ahead of predicate codes if necessary. But the logic to see if it is needed to put the null check fails because the attribute `a`  in the predicate `a.b > 1` is not the child of `IsNotNull` now. We should check if the attribute is referred by the `IsNotNull` instead.

## How was this patch tested?

Added a related test.

### CODE REVIEW

**Comment by mallman** [comment]
@viirya Please rebase your PR. I forgot that rebasing my PR would mess up this PR.

Or cherry-pick your commit onto the new head of my branch. That's probably easier.

**Comment by mallman** [comment]
Your commit LGTM. I can cherry pick it and push directly to my branch, or if you want to go through github's PR mechanism we can do that, too.

**Comment by mallman** [comment]
> Your commit LGTM. I can cherry pick it and push directly to my branch, or if you want to go through github's PR mechanism we can do that, too.

I accidentally pushed your commit manually. I was going to approve the PR anyway. I'm going to close this. Thanks for the fix!

**Comment by viirya** [comment]
@mallman Thanks for accepting the fix!

**Pull request closed without merging**
